---
title: "20200703 KA Tracing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(readxl)
library(tidyverse)
library(ggraph)
library(igraph)
library(ggrepel)
setwd("~/Documents/GitHub/tracing")
```

#Import data
```{r}
dat <- read_csv("KAtrace.csv",  skip = 19)
dat$Date <- as.Date(dat$Date, "%d-%b")
```

# Data processing

## Number of daily cases
```{r}
daily <- dat %>% group_by(Date) %>% summarize(Cases = n())
write_csv(daily, "daily_cases.csv")
```


## Classifying biggest clusters
```{r}
dat <- dat %>% group_by(Cluster) %>% mutate(n_cluster = n())
dat %>% group_by(Cluster) %>% summarize(n_cluster = n())
dat$origin_1 <- ifelse(dat$n_cluster < 100, "Others", as.character(dat$Cluster))
dat$origin_2 <- ifelse(dat$n_cluster < 200, "Others", as.character(dat$Cluster))
```

# Visualizations

## Stacked histogram, date, number and breakdown of cluster
```{r}
dat %>% filter(Cluster != "29-June Trace History Absent" & Cluster != "28-June Trace History Absent" & Cluster != "27-June Trace History Absent") %>% ggplot(aes(Date)) + geom_bar(position = "fill", aes(fill=origin_1), alpha = 0.7, color = "black", size = 0.1) + theme_classic() + theme(legend.position="bottom") + scale_fill_brewer(palette="Dark2", direction = 1) + ggtitle("Distribution of cases diagnosed from various clusters over time") + ylab("Proportion of cases confirmed daily")
ggsave("clusters_stacked.png")

dat %>% filter(Cluster != "29-June Trace History Absent" & Cluster != "28-June Trace History Absent" & Cluster != "27-June Trace History Absent") %>% ggplot(aes(Date)) + geom_bar( aes(fill=origin_2), alpha = 0.7) + theme_classic() + theme(legend.position="bottom") + scale_fill_brewer(palette="Dark2") + ggtitle("Distribution of cases diagnosed from various clusters over time") + ylab("Number of cases confirmed daily")
ggsave("clusters_pct.png")
```  
```{r}
dat %>% filter(Date < "2020-05-31") %>% ggplot(aes(Date)) + geom_bar( aes(fill=origin_1), alpha = 0.7) + theme_classic() + theme(legend.position="bottom") + scale_fill_brewer(palette="Dark2") + ggtitle("Distribution of cases diagnosed from various clusters over time") + ylab("Number of cases")
```

## Distibution of number of people infected by one person

### Data wrangle
```{r}
secondary <- dat %>% group_by(P) %>% summarize(`Secondary infections` = n()) 
write_csv(secondary, "secondary_infections.csv")

june26_parent <- secondary %>% filter(P <= 11005 & P != 0)
june26_parent %>% summarise(mean = mean(`Secondary infections`))
```
### Viz
```{r}
secondary %>% filter(`Secondary infections` < 100) %>% summarize(avg = mean(`Secondary infections`), med = median(`Secondary infections`))
june26_parent %>% filter(`Secondary infections` < 100) %>% ggplot(aes(`Secondary infections`)) + geom_histogram() + geom_vline(aes(xintercept = 3.075967, color = "Mean"), linetype="dashed") + theme_classic() + xlab("Number of infections caused by each patient") + ylab("Number of COVID-19 patients") + ggtitle("Distribution of number of  infections caused")
ggsave("secondary_hist.png")
```



# Network map

## Creating an edge list for Gephi

## Edge list for viz in R
```{r}
names(edges) <- c("Source", "Target")
write_csv(edges, "edge_gephi.csv")

nodes <- dat %>% ungroup() %>% select(Case, Cluster) 
names(nodes) <- c("Id", "Label")
nodes$`node-type` <- dat$Cluster
write_csv(nodes, "nodes_gephi.csv")
```

```{r}
edges <- dat %>% ungroup() %>% select(P, Case) 
edges$P <- ifelse(edges$P == 0, -as.numeric(dat$Cluster), edges$P)
names(edges) <- c("From", "To")
write_csv(edges, "edge_viz.csv")
```

## Edge list diagrams
```{r}
mygraph <- graph_from_edgelist(as.matrix(edges))

# With igraph
plot(mygraph, vertex.label="", edge.arrow.size=0, vertex.size=2)
 
# With ggraph:
ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_link() +
  theme_void()
 
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal() +
  theme_void()
```

